### ISSUE TITLE
@models.permalink no longer supported

### ISSUE THREAD

**Issue by litobro** [Pierre-Sassoulas/django-survey#15]
In survey/models @models.permalink has been deprecated since Django 1.11. It was recommended to be changed to a reverse call inside of the function instead. In Django 2.1, the decorator simply fails.

**Comment by Pierre-Sassoulas** [comment]
Thank you for this issue as well as #16 and #17. Right now we don't handle django 2.0. because I delayed the transition to python 3 and django 2.0 for some time. I need to do some work before being able to handle django 2.0 properly, see #18. I'm planning to do the transition properly, but it might takes some time. If you want to fix the project so it handle django 2.0 right now without bothering with #18, I can merge your change in a python 3+ only branch.

**Comment by Pierre-Sassoulas** [comment]
Fixed by https://github.com/Pierre-Sassoulas/django-survey/commit/e58b3877ab51f64f00ab2ad6f635446cac4c9037
