### ISSUE TITLE
Aggregating results

### ISSUE THREAD

**Issue by 1000camels** [Pierre-Sassoulas/django-survey#38]
I appreciate this might be out of scope, but I thought I would ask here first.

I am trying to build an admin summary of the results, grouping ChoiceFields by their answer. I've been having some trouble getting the csv, tex and pdf reports working, so I am unable to sort out how this data is aggregated or whether it is.

Has anyone developed a way to display a count of the answers for each question?

**Comment by Pierre-Sassoulas** [comment]
Well the csv or pdf report export is what you need from a user perspective. They're supposed to work, in particular the csv exporter do not have dependencies. Did you launch `python manage.py exportresult -h` ?

If it does not works, you can get a dictionary using `python manage.py shell` then the following code:

```
survey = None # Get your survey here
for response in survey.responses.all():
    for answer in response.answers.all():
        # Answers object have a "values" property that return a dict with answers as keys. 
        print(answer.values)
```

You could also create your own Survey2X exporter with blackjack and hookers.

**Comment by Pierre-Sassoulas** [comment]
Reopened because if its a bug or lack of documentation with export we should fix it.

**Comment by 1000camels** [comment]
There is definitely some confusion on my part. Perhaps I do not understand the process behind creating the PDF.

**Comment by Pierre-Sassoulas** [comment]
In order to generate the pdf you need `LaTeX` installed and also `python-3-tk`. You then can generate it, with `python manage.py exportresult -h`. Please see the full documentation here if you want to personalize it : https://github.com/Pierre-Sassoulas/django-survey#generating-a-pdf-report-from-the-surveys-result.

Let me know if something does'nt work or is'nt clear in the documentation.
