### ISSUE TITLE
export finishes without error and without exported file

### ISSUE THREAD

**Issue by gjelsas** [Pierre-Sassoulas/django-survey#55]
First a big thank you for your work!
When I try to export a report, I get no error message, but I also do not get a file. How do I  specify a filename or an export-location?
The command I'm using is:`python manage.py exportresult -c conf.yaml --survey-id 1 --tex`

**Comment by Pierre-Sassoulas** [comment]
Hello, thank you for using this library.

I think the default export folder for LaTeX is `tex` at the root of the project. The location can be changed, but not easily it seems, as the directory name is defined with the class name (for example Survey2Pdf will export in the "pdf" directory). In hindsight this look like an odd design choice on my part. You could try to inherit from `Survey2Tex` and choose another name for example `Survey2MyDirectory`. It would probably be better to refactor the exporters in order to permit to give an option to the `Survey2x` class (or a lot easier to just keep this default directory).

See for yourself here : 
Getting filename from class name : https://github.com/Pierre-Sassoulas/django-survey/blob/master/survey/exporter/survey2x.py#L29 and https://github.com/Pierre-Sassoulas/django-survey/blob/master/survey/exporter/survey2x.py#L35
Using the filename to generate the tex file : https://github.com/Pierre-Sassoulas/django-survey/blob/master/survey/exporter/tex/survey2tex.py#L128
Using the exporter from the management command : https://github.com/Pierre-Sassoulas/django-survey/blob/master/survey/management/commands/exportresult.py#L78

**Comment by gjelsas** [comment]
I think I messed up my installation although I did it via `pip install`! Tried to pull the repository, and now it works like a charm. 
Thanks again!
